spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
    url: jdbc:mysql://localhost:3306/retail_service
    username: root
    password: root123456
    hikari:
      idleTimeout: 600000 #Default
      cachePrepStmts: true
      maximumPoolSize: 5
      minimumIdle: 2
      prepStmtCacheSize: 256
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      connection-timeout: 30000
      poolName: wctestPool
      leakDetectionThreshold: 30000
#TODO: Connection keep alive config








